rootLogger.level = warn
rootLogger.appenderRef.console.ref = console

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n%ex

logger.NativeCodeLoader.name = org.apache.hadoop.util.NativeCodeLoader
logger.NativeCodeLoader.level = error

logger.GCMetrics.name = org.apache.spark.metrics.GarbageCollectionMetrics
logger.GCMetrics.level = error


logger.SparkStringUtils.name = org.apache.spark.util.SparkStringUtils
logger.SparkStringUtils.level = error
